### PR TITLE
fixes the invliad stack crash some times

### PR DESCRIPTION
**Pull request by Lioncky**
Useful with an indescribable scene, but need more time(8%~15% origin load time).
Perhaps we should treat the stack more safely?

### CODE REVIEW

**Comment by praydog** [comment]
I'm sorry... what? Can you describe in more detail what this is fixing? I don't know what stack crash this is referring to. Is there a dump I can look at? I'm not convinced that replacing all of the IsBadReadPtr calls with *more* logic, especially with a `VirtualQuery` call is going to improve performance.

**Comment by KsaNL** [comment]
This patch is not useful with Steam legal game, I don't known why Empress caused this, maybe we should do this otherwise dev tools can't work completely.

**Comment by praydog** [comment]
Rejected. Tested out the code and performance with Lua scripts drops as much as 1000%. This is not an exaggeration.

If you want the reason why, it's because Lua scripts call `is_managed_object` a lot behind the scenes to verify if something is a managed object. There are other functions too but they are more minor. 

https://github.com/praydog/REFramework/blob/master/shared/sdk/REManagedObject.cpp#L192

Replacing `IsBadReadPtr` with multiple `VirtualQuery` calls that span the size range is going to be much worse on performance on code.

The normal implementation of `IsBadReadPtr` essentially does this, which basically has no performance impact:
```cpp
try {
   for (auto i = 0; i < size; ++i) {
      auto asdf = *(uint8_t*)(ptr + i);
    }
} catch(...) {
}
```

**Comment by KsaNL** [comment]
Okay.

**Pull request closed without merging**
