### PR TITLE
Dependencies Update

### PR DESCRIPTION
**Pull request by KsaNL**
Update imgui and other dependencies to lastest edition

### CODE REVIEW

**Comment by praydog** [comment]
Unexpected issues with math being changed in this commit after the GLM update. Tentatively placing it in another branch. Might not merge.

**Comment by KsaNL** [comment]
Never mind, can't build directly yesterday, now build successful.
image

**Comment by praydog** [comment]
Think I've figured out the issue with the math. I'll work on it and merge it to master if there's no issues.

**Comment by KsaNL** [comment]
Sounds nice, best wishes :)

**Pull request merged**
