### PR TITLE
RE2/RE3 fixes, Joystick Smoothing, Smooth Locomotion

### PR DESCRIPTION
**Pull request by sibest**
- Fixed the new rendering method to work with RE2/RE3. Probably fixes the RE8 inventory stuck (to-be-tested)
- Added an option to smooth the joystick movement and prevent shaking
- Added an option to enable Smooth Locomotion in VR (RE2/RE3)
- Added an option to hide the head and neck (RE2/RE3)

### CODE REVIEW

**Comment by ZioPao** [comment]
I tested RE8, the inventory bug is still present.

**Comment by sibest** [comment]
How do you reproduce the inventory bug ? I've changed a mutex behaviour that can cause that but i need the steps to reproduce the freeze if possible.

**Comment by sibest** [comment]
Hi! Please try the new commit and let me know!

**Comment by ZioPao** [comment]
> Hi! Please try the new commit and let me know!

Hey, just tried it. Same results as before. Flickering that didn't happen in other builds and the inventory glitch is still there.
For the step, well, there's another issue which describes perfectly how to reproduce it
https://github.com/praydog/REFramework/issues/773
As you can see, it's not really hard to get it to happen.

**Pull request closed without merging**
